---
    - name: Create /usr/local/nvm directory
      file:
        path: /usr/local/nvm
        state: directory
        mode: '0755'

    - name: Install NVM globally
      shell: |
        export NVM_DIR="/usr/local/nvm"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: /usr/local/nvm/nvm.sh

    - name: Ensure /etc/profile.d directory exists
      file:
        path: /etc/profile.d
        state: directory
        mode: '0755'

    - name: Create /etc/profile.d/nvm.sh file if it doesn't exist
      file:
        path: /etc/profile.d/nvm.sh
        state: touch
        mode: '0644'

    - name: Set NVM environment variables for all users
      lineinfile:
        path: /etc/profile.d/nvm.sh
        line: |
          export NVM_DIR="/usr/local/nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  
          [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" 
      become: yes

    - name: Install Node.js 12
      shell: |
        . /usr/local/nvm/nvm.sh
        nvm install 12
      args:
        executable: /bin/bash

    - name: Install Node.js 16
      shell: |
        . /usr/local/nvm/nvm.sh
        nvm install 16
      args:
        executable: /bin/bash
    
    - name: Install Node.js 18
      shell: |
        . /usr/local/nvm/nvm.sh
        nvm install 18
      args:
        executable: /bin/bash

    - name: Set Node.js 12 as default for all users
      shell: |
        . /usr/local/nvm/nvm.sh
        nvm alias default 12
      args:
        executable: /bin/bash

