---
- name: deploy Traefik and Nginx
  ansible.builtin.copy:
    content: |
      version: '3'
      services:
        traefik:
          image: "traefik:{{traefik_version}}"
          container_name: traefik
          ports:
            - "80:80"
            - "8080:8080"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          command: --api.insecure=true --providers.docker
      nginx:
        image: "nginx:{{ nginx_version }}"
        container_name: nginx
        labels:
          - "traefik.http.routers.nginx.rule=Host(`example.com`)"
          - "traefik.http.services.nginx.loadbalancer.server.port=80"
    dest: /opt/docker-compose.yml
