---
# vars file for project

users:
  - name: user1
    shell: /bin/bash
  - name: user2
    shell: /bin/bash
  
static_ip: "192.168.1.100"
gateway: "192.168.1.1"
dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
routes:
  - network: "10.0.0.0/24"
    gateway: "192.168.1.1"
  - network: "192.168.2.0/24" 
    gateway: "192.168.1.1"
docker_compose_version: "v2.24.5"
traefik_version: "latest"
nginx_version: "latest"
